# Generated by Django 4.2.4 on 2023-08-26 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0002_category_alter_dog_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='birth_day',
            field=models.DateField(blank=True, null=True, verbose_name='Дата Рождения'),
        ),
    ]
